language: R
r_github_packages:
  - r-lib/lobstr
  - allisonhorst/palmerpenguins
r: bioc-release
sudo: false

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files
    - $HOME/.npm

before_install:
  - mkdir ~/.R
  - cp Makevars ~/.R
  - nvm install stable
  - npm install netlify-cli -g

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'
  - Rscript -e 'file.copy("_redirects", bookdown:::output_dirname(NULL))'

pandoc_version: 2.1.1

deploy:
  provider: script
  script: netlify deploy --dir="_book/" --prod
  skip_cleanup: true
  on:
    branch: main

notifications:
  email:
    - $EMAIL_TAZ
    - $EMAIL_HB